/**
 * Centrais nucleares do mundo — dataset curado manualmente (referência
 * estática, mesmo modelo do modo Osiris). Uso sobrevivencialista: consciência
 * de proximidade a instalações radiológicas em cenários de crise, conflito ou
 * desastre (falha, acidente ou zona de combate). Coordenadas aproximadas do
 * sítio. Capacidade em MW elétricos instalados; reatores operacionais.
 */

export type StatusNuclear = "operacional" | "em-construcao" | "acidentada" | "descomissionamento";

export interface CentralNuclear {
  id: string;
  nome: string;
  pais: string;
  lng: number;
  lat: number;
  reatores: number;
  /** Capacidade elétrica instalada em MW (aprox.). */
  capacidadeMW: number;
  status: StatusNuclear;
  /** Observação curta em pt-BR (opcional). */
  nota?: string;
}

export const ROTULO_STATUS_NUCLEAR: Record<StatusNuclear, string> = {
  operacional: "Operacional",
  "em-construcao": "Em construção",
  acidentada: "Acidentada",
  descomissionamento: "Em descomissionamento",
};

export const CENTRAIS_NUCLEARES: CentralNuclear[] = [
  // América
  {
    id: "angra",
    nome: "Angra dos Reis",
    pais: "Brasil",
    lng: -44.46,
    lat: -23.01,
    reatores: 2,
    capacidadeMW: 1990,
    status: "operacional",
    nota: "Angra 3 em obras paralisadas; única usina nuclear da América do Sul brasileira.",
  },
  {
    id: "atucha",
    nome: "Atucha",
    pais: "Argentina",
    lng: -59.21,
    lat: -34.0,
    reatores: 2,
    capacidadeMW: 1003,
    status: "operacional",
  },
  {
    id: "embalse",
    nome: "Embalse",
    pais: "Argentina",
    lng: -64.44,
    lat: -32.23,
    reatores: 1,
    capacidadeMW: 648,
    status: "operacional",
  },
  {
    id: "palo-verde",
    nome: "Palo Verde",
    pais: "EUA",
    lng: -112.87,
    lat: 33.39,
    reatores: 3,
    capacidadeMW: 3993,
    status: "operacional",
    nota: "Maior gerador nuclear dos EUA; refrigerada por águas residuais.",
  },
  {
    id: "vogtle",
    nome: "Vogtle",
    pais: "EUA",
    lng: -81.76,
    lat: 33.14,
    reatores: 4,
    capacidadeMW: 4100,
    status: "operacional",
  },
  {
    id: "browns-ferry",
    nome: "Browns Ferry",
    pais: "EUA",
    lng: -87.12,
    lat: 34.7,
    reatores: 3,
    capacidadeMW: 3396,
    status: "operacional",
  },
  {
    id: "south-texas",
    nome: "South Texas",
    pais: "EUA",
    lng: -96.05,
    lat: 28.8,
    reatores: 2,
    capacidadeMW: 2645,
    status: "operacional",
  },
  {
    id: "peach-bottom",
    nome: "Peach Bottom",
    pais: "EUA",
    lng: -76.27,
    lat: 39.76,
    reatores: 2,
    capacidadeMW: 2775,
    status: "operacional",
  },
  {
    id: "braidwood",
    nome: "Braidwood",
    pais: "EUA",
    lng: -88.22,
    lat: 41.24,
    reatores: 2,
    capacidadeMW: 2386,
    status: "operacional",
  },
  {
    id: "byron",
    nome: "Byron",
    pais: "EUA",
    lng: -89.26,
    lat: 41.72,
    reatores: 2,
    capacidadeMW: 2347,
    status: "operacional",
  },
  {
    id: "diablo-canyon",
    nome: "Diablo Canyon",
    pais: "EUA",
    lng: -120.76,
    lat: 35.66,
    reatores: 2,
    capacidadeMW: 2240,
    status: "operacional",
    nota: "Costa da Califórnia, zona de falha sismica — referência de risco.",
  },
  {
    id: "limerick",
    nome: "Limerick",
    pais: "EUA",
    lng: -75.59,
    lat: 40.22,
    reatores: 2,
    capacidadeMW: 2317,
    status: "operacional",
  },
  {
    id: "oconee",
    nome: "Oconee",
    pais: "EUA",
    lng: -82.9,
    lat: 34.79,
    reatores: 3,
    capacidadeMW: 2538,
    status: "operacional",
  },
  {
    id: "turkey-point",
    nome: "Turkey Point",
    pais: "EUA",
    lng: -80.33,
    lat: 25.44,
    reatores: 2,
    capacidadeMW: 1791,
    status: "operacional",
    nota: "Na trajetória de furacões do Golfo/Mar do Caribe.",
  },
  {
    id: "bruce",
    nome: "Bruce",
    pais: "Canadá",
    lng: -81.6,
    lat: 44.32,
    reatores: 8,
    capacidadeMW: 6520,
    status: "operacional",
    nota: "Maior parque nuclear do mundo em número de reatores ativos.",
  },
  {
    id: "darlington",
    nome: "Darlington",
    pais: "Canadá",
    lng: -78.71,
    lat: 43.87,
    reatores: 4,
    capacidadeMW: 3512,
    status: "operacional",
  },
  {
    id: "pickering",
    nome: "Pickering",
    pais: "Canadá",
    lng: -79.07,
    lat: 43.81,
    reatores: 6,
    capacidadeMW: 3100,
    status: "operacional",
  },
  {
    id: "laguna-verde",
    nome: "Laguna Verde",
    pais: "México",
    lng: -96.41,
    lat: 19.72,
    reatores: 2,
    capacidadeMW: 1610,
    status: "operacional",
  },
  // Europa
  {
    id: "gravelines",
    nome: "Gravelines",
    pais: "França",
    lng: 2.13,
    lat: 51.02,
    reatores: 6,
    capacidadeMW: 5460,
    status: "operacional",
  },
  {
    id: "paluel",
    nome: "Paluel",
    pais: "França",
    lng: 0.63,
    lat: 49.86,
    reatores: 4,
    capacidadeMW: 5320,
    status: "operacional",
  },
  {
    id: "cattenom",
    nome: "Cattenom",
    pais: "França",
    lng: 6.22,
    lat: 49.42,
    reatores: 4,
    capacidadeMW: 5200,
    status: "operacional",
    nota: "Próxima à fronteira de Luxemburgo/Alemanha.",
  },
  {
    id: "blayais",
    nome: "Blayais",
    pais: "França",
    lng: -0.66,
    lat: 45.26,
    reatores: 4,
    capacidadeMW: 3640,
    status: "operacional",
  },
  {
    id: "bugey",
    nome: "Bugey",
    pais: "França",
    lng: 5.27,
    lat: 45.8,
    reatores: 4,
    capacidadeMW: 3580,
    status: "operacional",
  },
  {
    id: "cruas",
    nome: "Cruas",
    pais: "França",
    lng: 4.76,
    lat: 44.63,
    reatores: 4,
    capacidadeMW: 3660,
    status: "operacional",
  },
  {
    id: "tricastin",
    nome: "Tricastin",
    pais: "França",
    lng: 4.73,
    lat: 44.33,
    reatores: 4,
    capacidadeMW: 3660,
    status: "operacional",
    nota: "Complexo com enriquecimento de urânio no mesmo polo.",
  },
  {
    id: "chinon",
    nome: "Chinon",
    pais: "França",
    lng: 0.17,
    lat: 47.23,
    reatores: 4,
    capacidadeMW: 3620,
    status: "operacional",
  },
  {
    id: "flamanville",
    nome: "Flamanville",
    pais: "França",
    lng: -1.88,
    lat: 49.54,
    reatores: 3,
    capacidadeMW: 3660,
    status: "operacional",
  },
  {
    id: "heysham",
    nome: "Heysham",
    pais: "Reino Unido",
    lng: -2.91,
    lat: 54.03,
    reatores: 4,
    capacidadeMW: 2400,
    status: "operacional",
  },
  {
    id: "sizewell",
    nome: "Sizewell B",
    pais: "Reino Unido",
    lng: 1.62,
    lat: 52.21,
    reatores: 1,
    capacidadeMW: 1198,
    status: "operacional",
  },
  {
    id: "torness",
    nome: "Torness",
    pais: "Reino Unido",
    lng: -2.41,
    lat: 55.97,
    reatores: 2,
    capacidadeMW: 1200,
    status: "operacional",
  },
  {
    id: "hinkley-c",
    nome: "Hinkley Point C",
    pais: "Reino Unido",
    lng: -3.13,
    lat: 51.21,
    reatores: 2,
    capacidadeMW: 3260,
    status: "em-construcao",
  },
  {
    id: "almaraz",
    nome: "Almaraz",
    pais: "Espanha",
    lng: -5.7,
    lat: 39.81,
    reatores: 2,
    capacidadeMW: 2017,
    status: "operacional",
  },
  {
    id: "cofrentes",
    nome: "Cofrentes",
    pais: "Espanha",
    lng: -1.05,
    lat: 39.22,
    reatores: 1,
    capacidadeMW: 1092,
    status: "operacional",
  },
  {
    id: "asco",
    nome: "Ascó",
    pais: "Espanha",
    lng: 0.57,
    lat: 41.2,
    reatores: 2,
    capacidadeMW: 1982,
    status: "operacional",
  },
  {
    id: "doel",
    nome: "Doel",
    pais: "Bélgica",
    lng: 4.26,
    lat: 51.32,
    reatores: 4,
    capacidadeMW: 2734,
    status: "operacional",
    nota: "Próxima a Antuérpia; desativação programada em discussão.",
  },
  {
    id: "tihange",
    nome: "Tihange",
    pais: "Bélgica",
    lng: 5.27,
    lat: 50.53,
    reatores: 3,
    capacidadeMW: 2014,
    status: "operacional",
  },
  {
    id: "forsmark",
    nome: "Forsmark",
    pais: "Suécia",
    lng: 18.17,
    lat: 60.4,
    reatores: 3,
    capacidadeMW: 3262,
    status: "operacional",
  },
  {
    id: "ringhals",
    nome: "Ringhals",
    pais: "Suécia",
    lng: 12.11,
    lat: 57.26,
    reatores: 4,
    capacidadeMW: 2160,
    status: "operacional",
  },
  {
    id: "oskarshamn",
    nome: "Oskarshamn",
    pais: "Suécia",
    lng: 16.67,
    lat: 57.42,
    reatores: 2,
    capacidadeMW: 1454,
    status: "operacional",
  },
  {
    id: "olkiluoto",
    nome: "Olkiluoto",
    pais: "Finlândia",
    lng: 21.44,
    lat: 61.24,
    reatores: 3,
    capacidadeMW: 2860,
    status: "operacional",
  },
  {
    id: "loviisa",
    nome: "Loviisa",
    pais: "Finlândia",
    lng: 26.35,
    lat: 60.37,
    reatores: 2,
    capacidadeMW: 1020,
    status: "operacional",
    nota: "Fronteira marítima com a Rússia (Golfo da Finlândia).",
  },
  {
    id: "temelin",
    nome: "Temelín",
    pais: "Tchéquia",
    lng: 14.37,
    lat: 49.18,
    reatores: 2,
    capacidadeMW: 2160,
    status: "operacional",
  },
  {
    id: "dukovany",
    nome: "Dukovany",
    pais: "Tchéquia",
    lng: 16.15,
    lat: 49.08,
    reatores: 4,
    capacidadeMW: 2040,
    status: "operacional",
  },
  {
    id: "mochovce",
    nome: "Mochovce",
    pais: "Eslováquia",
    lng: 18.46,
    lat: 48.26,
    reatores: 4,
    capacidadeMW: 1940,
    status: "operacional",
  },
  {
    id: "bohunice",
    nome: "Jaslovské Bohunice",
    pais: "Eslováquia",
    lng: 17.68,
    lat: 48.49,
    reatores: 2,
    capacidadeMW: 1008,
    status: "operacional",
  },
  {
    id: "paks",
    nome: "Paks",
    pais: "Hungria",
    lng: 18.85,
    lat: 46.57,
    reatores: 4,
    capacidadeMW: 2000,
    status: "operacional",
  },
  {
    id: "cernavoda",
    nome: "Cernavodă",
    pais: "Romênia",
    lng: 28.03,
    lat: 44.32,
    reatores: 2,
    capacidadeMW: 1410,
    status: "operacional",
    nota: "No Danúbio, a ~200 km do Mar Negro.",
  },
  {
    id: "kozloduy",
    nome: "Kozloduy",
    pais: "Bulgária",
    lng: 23.77,
    lat: 43.75,
    reatores: 2,
    capacidadeMW: 2000,
    status: "operacional",
  },
  {
    id: "krsko",
    nome: "Krško",
    pais: "Eslovênia",
    lng: 15.52,
    lat: 45.94,
    reatores: 1,
    capacidadeMW: 727,
    status: "operacional",
  },
  {
    id: "leibstadt",
    nome: "Leibstadt",
    pais: "Suíça",
    lng: 8.18,
    lat: 47.6,
    reatores: 1,
    capacidadeMW: 1220,
    status: "operacional",
  },
  {
    id: "gosgen",
    nome: "Gösgen",
    pais: "Suíça",
    lng: 7.97,
    lat: 47.37,
    reatores: 1,
    capacidadeMW: 1020,
    status: "operacional",
  },
  {
    id: "beznau",
    nome: "Beznau",
    pais: "Suíça",
    lng: 8.23,
    lat: 47.55,
    reatores: 2,
    capacidadeMW: 740,
    status: "operacional",
  },
  // Ucrânia e Rússia (zona de guerra — monitorar)
  {
    id: "zaporijia",
    nome: "Zaporíjia",
    pais: "Ucrânia",
    lng: 34.59,
    lat: 47.51,
    reatores: 6,
    capacidadeMW: 5700,
    status: "operacional",
    nota: "Maior da Europa; ocupada pela Rússia desde 2022 — zona de combate e corte de energia reiterado.",
  },
  {
    id: "rivne",
    nome: "Rivne",
    pais: "Ucrânia",
    lng: 25.89,
    lat: 51.33,
    reatores: 4,
    capacidadeMW: 1420,
    status: "operacional",
  },
  {
    id: "khmelnytskyi",
    nome: "Khmelnytskyi",
    pais: "Ucrânia",
    lng: 26.65,
    lat: 50.3,
    reatores: 2,
    capacidadeMW: 2000,
    status: "operacional",
  },
  {
    id: "pivdennoukrainsk",
    nome: "Pivdennoukrainsk (South Ukraine)",
    pais: "Ucrânia",
    lng: 31.22,
    lat: 47.81,
    reatores: 3,
    capacidadeMW: 3000,
    status: "operacional",
  },
  {
    id: "balakovo",
    nome: "Balakovo",
    pais: "Rússia",
    lng: 47.95,
    lat: 52.09,
    reatores: 4,
    capacidadeMW: 4000,
    status: "operacional",
  },
  {
    id: "leningrado",
    nome: "Leningrado",
    pais: "Rússia",
    lng: 29.04,
    lat: 59.85,
    reatores: 4,
    capacidadeMW: 4200,
    status: "operacional",
  },
  {
    id: "kursk",
    nome: "Kursk",
    pais: "Rússia",
    lng: 36.28,
    lat: 51.68,
    reatores: 4,
    capacidadeMW: 2000,
    status: "operacional",
    nota: "Região de frente na guerra — drons atingiram a área em 2024–2025.",
  },
  {
    id: "rostov",
    nome: "Rostov (Volgodonsk)",
    pais: "Rússia",
    lng: 42.39,
    lat: 47.59,
    reatores: 4,
    capacidadeMW: 4000,
    status: "operacional",
  },
  {
    id: "smolensk",
    nome: "Smolensk",
    pais: "Rússia",
    lng: 33.23,
    lat: 54.2,
    reatores: 3,
    capacidadeMW: 3000,
    status: "operacional",
  },
  {
    id: "novovoronezh",
    nome: "Novovoronezh",
    pais: "Rússia",
    lng: 39.21,
    lat: 51.28,
    reatores: 4,
    capacidadeMW: 1880,
    status: "operacional",
  },
  {
    id: "beloyarsk",
    nome: "Beloyarsk",
    pais: "Rússia",
    lng: 61.32,
    lat: 56.84,
    reatores: 2,
    capacidadeMW: 1480,
    status: "operacional",
    nota: "Reatores rápidos BN-600/BN-800.",
  },
  {
    id: "astravets",
    nome: "Astravets",
    pais: "Bielorrússia",
    lng: 26.13,
    lat: 54.24,
    reatores: 2,
    capacidadeMW: 2400,
    status: "operacional",
    nota: "A ~50 km da Lituânia/UE.",
  },
  {
    id: "metsamor",
    nome: "Metsamor",
    pais: "Armênia",
    lng: 44.16,
    lat: 40.18,
    reatores: 1,
    capacidadeMW: 440,
    status: "operacional",
    nota: "Zona sísmica ativa; antiga soviética VVER-440.",
  },
  {
    id: "akkuyu",
    nome: "Akkuyu",
    pais: "Turquia",
    lng: 32.93,
    lat: 36.15,
    reatores: 4,
    capacidadeMW: 4800,
    status: "em-construcao",
    nota: "Construída e operada pela Rússia (Rosatom).",
  },
  // Ásia e Oceania
  {
    id: "kori",
    nome: "Kori / Shin-Kori",
    pais: "Coreia do Sul",
    lng: 129.29,
    lat: 35.32,
    reatores: 8,
    capacidadeMW: 6400,
    status: "operacional",
  },
  {
    id: "hanul",
    nome: "Hanul (Uljin)",
    pais: "Coreia do Sul",
    lng: 129.39,
    lat: 37.09,
    reatores: 8,
    capacidadeMW: 6800,
    status: "operacional",
  },
  {
    id: "hanbit",
    nome: "Hanbit (Yonggwang)",
    pais: "Coreia do Sul",
    lng: 126.42,
    lat: 35.44,
    reatores: 6,
    capacidadeMW: 5875,
    status: "operacional",
  },
  {
    id: "wolsong",
    nome: "Wolsong / Shin-Wolsong",
    pais: "Coreia do Sul",
    lng: 129.45,
    lat: 37.06,
    reatores: 6,
    capacidadeMW: 4000,
    status: "operacional",
  },
  {
    id: "kashiwazaki",
    nome: "Kashiwazaki-Kariwa",
    pais: "Japão",
    lng: 138.6,
    lat: 37.43,
    reatores: 7,
    capacidadeMW: 7965,
    status: "operacional",
    nota: "Maior do mundo por capacidade; reinício gradual após checagens.",
  },
  {
    id: "fukushima-daiichi",
    nome: "Fukushima Daiichi",
    pais: "Japão",
    lng: 141.03,
    lat: 37.42,
    reatores: 0,
    capacidadeMW: 0,
    status: "acidentada",
    nota: "Acidente nível 7 (2011); descomissionamento de décadas, liberação de água tratada em curso.",
  },
  {
    id: "ohi",
    nome: "Ohi",
    pais: "Japão",
    lng: 135.65,
    lat: 35.54,
    reatores: 4,
    capacidadeMW: 4494,
    status: "operacional",
  },
  {
    id: "takahama",
    nome: "Takahama",
    pais: "Japão",
    lng: 135.5,
    lat: 35.52,
    reatores: 4,
    capacidadeMW: 3208,
    status: "operacional",
  },
  {
    id: "genkai",
    nome: "Genkai",
    pais: "Japão",
    lng: 129.84,
    lat: 33.52,
    reatores: 4,
    capacidadeMW: 3460,
    status: "operacional",
  },
  {
    id: "sendai-jp",
    nome: "Sendai (Kagoshima)",
    pais: "Japão",
    lng: 130.19,
    lat: 31.83,
    reatores: 2,
    capacidadeMW: 1780,
    status: "operacional",
  },
  {
    id: "ikata",
    nome: "Ikata",
    pais: "Japão",
    lng: 132.31,
    lat: 33.49,
    reatores: 3,
    capacidadeMW: 2022,
    status: "operacional",
  },
  {
    id: "yangjiang",
    nome: "Yangjiang",
    pais: "China",
    lng: 112.01,
    lat: 21.83,
    reatores: 6,
    capacidadeMW: 6100,
    status: "operacional",
  },
  {
    id: "taishan-cn",
    nome: "Taishan",
    pais: "China",
    lng: 112.99,
    lat: 21.92,
    reatores: 2,
    capacidadeMW: 3500,
    status: "operacional",
    nota: "EPR franceses — os mais potentes em operação comercial.",
  },
  {
    id: "daya-bay",
    nome: "Daya Bay / Ling Ao",
    pais: "China",
    lng: 114.54,
    lat: 22.6,
    reatores: 6,
    capacidadeMW: 6000,
    status: "operacional",
  },
  {
    id: "fuqing",
    nome: "Fuqing",
    pais: "China",
    lng: 119.45,
    lat: 25.45,
    reatores: 6,
    capacidadeMW: 5000,
    status: "operacional",
    nota: "Primeiro reator Hualong One comercial.",
  },
  {
    id: "ningde",
    nome: "Ningde",
    pais: "China",
    lng: 120.29,
    lat: 27.03,
    reatores: 4,
    capacidadeMW: 4280,
    status: "operacional",
  },
  {
    id: "qinshan",
    nome: "Qinshan",
    pais: "China",
    lng: 120.95,
    lat: 30.44,
    reatores: 7,
    capacidadeMW: 4460,
    status: "operacional",
  },
  {
    id: "tianwan",
    nome: "Tianwan",
    pais: "China",
    lng: 119.46,
    lat: 34.69,
    reatores: 6,
    capacidadeMW: 4000,
    status: "operacional",
    nota: "Projeto sino-russo.",
  },
  {
    id: "haiyang",
    nome: "Haiyang",
    pais: "China",
    lng: 121.38,
    lat: 36.7,
    reatores: 4,
    capacidadeMW: 5000,
    status: "operacional",
  },
  {
    id: "kudankulam",
    nome: "Kudankulam",
    pais: "Índia",
    lng: 77.71,
    lat: 8.17,
    reatores: 2,
    capacidadeMW: 2000,
    status: "operacional",
    nota: "VVER russos; expansão em curso.",
  },
  {
    id: "tarapur",
    nome: "Tarapur",
    pais: "Índia",
    lng: 72.66,
    lat: 19.83,
    reatores: 4,
    capacidadeMW: 1400,
    status: "operacional",
  },
  {
    id: "rajasthan",
    nome: "Rajasthan (Rawatbhata)",
    pais: "Índia",
    lng: 75.61,
    lat: 24.87,
    reatores: 6,
    capacidadeMW: 1180,
    status: "operacional",
  },
  {
    id: "kaiga",
    nome: "Kaiga",
    pais: "Índia",
    lng: 74.44,
    lat: 14.87,
    reatores: 4,
    capacidadeMW: 880,
    status: "operacional",
  },
  {
    id: "kalpakkam",
    nome: "Madras (Kalpakkam)",
    pais: "Índia",
    lng: 80.17,
    lat: 12.56,
    reatores: 2,
    capacidadeMW: 640,
    status: "operacional",
    nota: "Foi atingida pelo tsunami de 2004.",
  },
  {
    id: "karachi",
    nome: "Karachi (KANUPP)",
    pais: "Paquistão",
    lng: 66.79,
    lat: 24.85,
    reatores: 2,
    capacidadeMW: 1100,
    status: "operacional",
    nota: "Megacidade costeira; risco de tsunami/ciclone.",
  },
  {
    id: "chashma",
    nome: "Chashma",
    pais: "Paquistão",
    lng: 71.46,
    lat: 32.39,
    reatores: 4,
    capacidadeMW: 1330,
    status: "operacional",
  },
  {
    id: "barakah",
    nome: "Barakah",
    pais: "Emirados Árabes",
    lng: 52.23,
    lat: 23.97,
    reatores: 4,
    capacidadeMW: 5600,
    status: "operacional",
  },
  {
    id: "bushehr",
    nome: "Bushehr",
    pais: "Irã",
    lng: 50.89,
    lat: 28.83,
    reatores: 1,
    capacidadeMW: 1000,
    status: "operacional",
    nota: "Zona de tensão militar com Israel; zona sísmica.",
  },
  {
    id: "maanshan",
    nome: "Maanshan",
    pais: "Taiwan",
    lng: 120.75,
    lat: 21.94,
    reatores: 2,
    capacidadeMW: 1900,
    status: "operacional",
    nota: "Fim do programa nuclear taiwanês previsto; ilha em rota de tufões.",
  },
  {
    id: "kuosheng",
    nome: "Kuosheng",
    pais: "Taiwan",
    lng: 121.66,
    lat: 25.2,
    reatores: 2,
    capacidadeMW: 1934,
    status: "descomissionamento",
  },
  {
    id: "koeberg",
    nome: "Koeberg",
    pais: "África do Sul",
    lng: 18.43,
    lat: -33.68,
    reatores: 2,
    capacidadeMW: 1860,
    status: "operacional",
    nota: "Única da África; costa perto da Cidade do Cabo.",
  },
  {
    id: "rooppur",
    nome: "Rooppur",
    pais: "Bangladesh",
    lng: 89.05,
    lat: 24.06,
    reatores: 2,
    capacidadeMW: 2400,
    status: "em-construcao",
    nota: "Delta densíssimo do Ganges — planejamento de evacuação é crítico.",
  },
];

/** Contagem por status para painéis/labels. */
export function resumoNuclear() {
  const total = CENTRAIS_NUCLEARES.length;
  const acidentadas = CENTRAIS_NUCLEARES.filter((c) => c.status === "acidentada").length;
  const emConstrucao = CENTRAIS_NUCLEARES.filter((c) => c.status === "em-construcao").length;
  return { total, acidentadas, emConstrucao };
}
