/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SosRouteImport } from './routes/sos'
import { Route as ManualIndexRouteImport } from './routes/manual.index'
import { Route as ManualSlugRouteImport } from './routes/manual.$slug'
import { Route as ApiPublicReportsWeeklyRouteImport } from './routes/api/public/reports-weekly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualIndexRoute = ManualIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManualRoute,
} as any)
const ManualSlugRoute = ManualSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ManualRoute,
} as any)
const ApiPublicReportsWeeklyRoute = ApiPublicReportsWeeklyRouteImport.update({
  id: '/api/public/reports-weekly',
  path: '/api/public/reports-weekly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRouteWithChildren
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/': typeof ManualIndexRoute
  '/api/public/reports-weekly': typeof ApiPublicReportsWeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual': typeof ManualIndexRoute
  '/api/public/reports-weekly': typeof ApiPublicReportsWeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRouteWithChildren
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/': typeof ManualIndexRoute
  '/api/public/reports-weekly': typeof ApiPublicReportsWeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/manual'
    | '/offline'
    | '/settings'
    | '/sos'
    | '/manual/$slug'
    | '/manual/'
    | '/api/public/reports-weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/offline'
    | '/settings'
    | '/sos'
    | '/manual/$slug'
    | '/manual'
    | '/api/public/reports-weekly'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/login'
    | '/manual'
    | '/offline'
    | '/settings'
    | '/sos'
    | '/manual/$slug'
    | '/manual/'
    | '/api/public/reports-weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  SettingsRoute: typeof SettingsRoute
  SosRoute: typeof SosRoute
  ApiPublicReportsWeeklyRoute: typeof ApiPublicReportsWeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/': {
      id: '/manual/'
      path: '/'
      fullPath: '/manual/'
      preLoaderRoute: typeof ManualIndexRouteImport
      parentRoute: typeof ManualRoute
    }
    '/manual/$slug': {
      id: '/manual/$slug'
      path: '/$slug'
      fullPath: '/manual/$slug'
      preLoaderRoute: typeof ManualSlugRouteImport
      parentRoute: typeof ManualRoute
    }
    '/api/public/reports-weekly': {
      id: '/api/public/reports-weekly'
      path: '/api/public/reports-weekly'
      fullPath: '/api/public/reports-weekly'
      preLoaderRoute: typeof ApiPublicReportsWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManualRouteChildren {
  ManualSlugRoute: typeof ManualSlugRoute
  ManualIndexRoute: typeof ManualIndexRoute
}

const ManualRouteChildren: ManualRouteChildren = {
  ManualSlugRoute: ManualSlugRoute,
  ManualIndexRoute: ManualIndexRoute,
}

const ManualRouteWithChildren =
  ManualRoute._addFileChildren(ManualRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRouteWithChildren,
  OfflineRoute: OfflineRoute,
  SettingsRoute: SettingsRoute,
  SosRoute: SosRoute,
  ApiPublicReportsWeeklyRoute: ApiPublicReportsWeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
