/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApoiarRouteImport } from './routes/apoiar'
import { Route as ColaboradoresRouteImport } from './routes/colaboradores'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DepositoRouteImport } from './routes/deposito'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SosRouteImport } from './routes/sos'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as ManualIndexRouteImport } from './routes/manual.index'
import { Route as ManualSlugRouteImport } from './routes/manual.$slug'
import { Route as ApiPublicReportsWeeklyRouteImport } from './routes/api/public/reports-weekly'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoiarRoute = ApoiarRouteImport.update({
  id: '/apoiar',
  path: '/apoiar',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboradoresRoute = ColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositoRoute = DepositoRouteImport.update({
  id: '/deposito',
  path: '/deposito',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualIndexRoute = ManualIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManualRoute,
} as any)
const ManualSlugRoute = ManualSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ManualRoute,
} as any)
const ApiPublicReportsWeeklyRoute = ApiPublicReportsWeeklyRouteImport.update({
  id: '/api/public/reports-weekly',
  path: '/api/public/reports-weekly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apoiar': typeof ApoiarRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/deposito': typeof DepositoRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRouteWithChildren
  '/notas': typeof NotasRoute
  '/offline': typeof OfflineRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/tutorial': typeof TutorialRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/': typeof ManualIndexRoute
  '/api/public/reports-weekly': typeof ApiPublicReportsWeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apoiar': typeof ApoiarRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/deposito': typeof DepositoRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/notas': typeof NotasRoute
  '/offline': typeof OfflineRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/tutorial': typeof TutorialRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual': typeof ManualIndexRoute
  '/api/public/reports-weekly': typeof ApiPublicReportsWeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apoiar': typeof ApoiarRoute
  '/colaboradores': typeof ColaboradoresRoute
  '/conta': typeof ContaRoute
  '/dashboard': typeof DashboardRoute
  '/deposito': typeof DepositoRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRouteWithChildren
  '/notas': typeof NotasRoute
  '/offline': typeof OfflineRoute
  '/parceiros': typeof ParceirosRoute
  '/perfil': typeof PerfilRoute
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/tutorial': typeof TutorialRoute
  '/manual/$slug': typeof ManualSlugRoute
  '/manual/': typeof ManualIndexRoute
  '/api/public/reports-weekly': typeof ApiPublicReportsWeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apoiar'
    | '/colaboradores'
    | '/conta'
    | '/dashboard'
    | '/deposito'
    | '/inventory'
    | '/login'
    | '/manual'
    | '/notas'
    | '/offline'
    | '/parceiros'
    | '/perfil'
    | '/settings'
    | '/sos'
    | '/tutorial'
    | '/manual/$slug'
    | '/manual/'
    | '/api/public/reports-weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apoiar'
    | '/colaboradores'
    | '/conta'
    | '/dashboard'
    | '/deposito'
    | '/inventory'
    | '/login'
    | '/notas'
    | '/offline'
    | '/parceiros'
    | '/perfil'
    | '/settings'
    | '/sos'
    | '/tutorial'
    | '/manual/$slug'
    | '/manual'
    | '/api/public/reports-weekly'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apoiar'
    | '/colaboradores'
    | '/conta'
    | '/dashboard'
    | '/deposito'
    | '/inventory'
    | '/login'
    | '/manual'
    | '/notas'
    | '/offline'
    | '/parceiros'
    | '/perfil'
    | '/settings'
    | '/sos'
    | '/tutorial'
    | '/manual/$slug'
    | '/manual/'
    | '/api/public/reports-weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApoiarRoute: typeof ApoiarRoute
  ColaboradoresRoute: typeof ColaboradoresRoute
  ContaRoute: typeof ContaRoute
  DashboardRoute: typeof DashboardRoute
  DepositoRoute: typeof DepositoRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRouteWithChildren
  NotasRoute: typeof NotasRoute
  OfflineRoute: typeof OfflineRoute
  ParceirosRoute: typeof ParceirosRoute
  PerfilRoute: typeof PerfilRoute
  SettingsRoute: typeof SettingsRoute
  SosRoute: typeof SosRoute
  TutorialRoute: typeof TutorialRoute
  ApiPublicReportsWeeklyRoute: typeof ApiPublicReportsWeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoiar': {
      id: '/apoiar'
      path: '/apoiar'
      fullPath: '/apoiar'
      preLoaderRoute: typeof ApoiarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboradores': {
      id: '/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof ColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposito': {
      id: '/deposito'
      path: '/deposito'
      fullPath: '/deposito'
      preLoaderRoute: typeof DepositoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/': {
      id: '/manual/'
      path: '/'
      fullPath: '/manual/'
      preLoaderRoute: typeof ManualIndexRouteImport
      parentRoute: typeof ManualRoute
    }
    '/manual/$slug': {
      id: '/manual/$slug'
      path: '/$slug'
      fullPath: '/manual/$slug'
      preLoaderRoute: typeof ManualSlugRouteImport
      parentRoute: typeof ManualRoute
    }
    '/api/public/reports-weekly': {
      id: '/api/public/reports-weekly'
      path: '/api/public/reports-weekly'
      fullPath: '/api/public/reports-weekly'
      preLoaderRoute: typeof ApiPublicReportsWeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ManualRouteChildren {
  ManualSlugRoute: typeof ManualSlugRoute
  ManualIndexRoute: typeof ManualIndexRoute
}

const ManualRouteChildren: ManualRouteChildren = {
  ManualSlugRoute: ManualSlugRoute,
  ManualIndexRoute: ManualIndexRoute,
}

const ManualRouteWithChildren =
  ManualRoute._addFileChildren(ManualRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApoiarRoute: ApoiarRoute,
  ColaboradoresRoute: ColaboradoresRoute,
  ContaRoute: ContaRoute,
  DashboardRoute: DashboardRoute,
  DepositoRoute: DepositoRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRouteWithChildren,
  NotasRoute: NotasRoute,
  OfflineRoute: OfflineRoute,
  ParceirosRoute: ParceirosRoute,
  PerfilRoute: PerfilRoute,
  SettingsRoute: SettingsRoute,
  SosRoute: SosRoute,
  TutorialRoute: TutorialRoute,
  ApiPublicReportsWeeklyRoute: ApiPublicReportsWeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
