/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManualSlugRouteImport } from './routes/manual.$slug'

const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualSlugRoute = ManualSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ManualRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/manual/$slug': typeof ManualSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/manual/$slug': typeof ManualSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/manual': typeof ManualRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sos': typeof SosRoute
  '/manual/$slug': typeof ManualSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inventory'
    | '/login'
    | '/manual'
    | '/settings'
    | '/sos'
    | '/manual/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventory'
    | '/login'
    | '/manual'
    | '/settings'
    | '/sos'
    | '/manual/$slug'
  id:
    | '__root__'
    | '/'
    | '/inventory'
    | '/login'
    | '/manual'
    | '/settings'
    | '/sos'
    | '/manual/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  ManualRoute: typeof ManualRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SosRoute: typeof SosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual/$slug': {
      id: '/manual/$slug'
      path: '/$slug'
      fullPath: '/manual/$slug'
      preLoaderRoute: typeof ManualSlugRouteImport
      parentRoute: typeof ManualRoute
    }
  }
}

interface ManualRouteChildren {
  ManualSlugRoute: typeof ManualSlugRoute
}

const ManualRouteChildren: ManualRouteChildren = {
  ManualSlugRoute: ManualSlugRoute,
}

const ManualRouteWithChildren =
  ManualRoute._addFileChildren(ManualRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  ManualRoute: ManualRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SosRoute: SosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
